meta_product_name: "CommitGame"
meta_title: "CommitGame - Gamify your coding side projects!"
meta_description: "Gamify your coding side projects!"
meta_image: "sitemeta.png" # should exist in `app/assets/images/`
